name: 'WireGuard'
description: 'Connect a WireGuard VPN client for a GitHub Actions runner'
branding:
  icon: 'lock'
  color: 'red'
inputs:
  interface_private_key:
    description: "The interface private key"
    required: true
  interface_address:
    description: "The interface address"
    required: true
  interface_dns:
    description: "The interface DNS"
    required: false
  peer_public_key:
    description: "The peer public key"
    required: true
  peer_allowed_ips:
    description: "The peer allowed IPs"
    required: true
  peer_endpoint:
    description: "The peer endpoint"
    required: true
runs:
  using: "composite"
  steps:
    - name: Install wireguard
      shell: bash
      run: sudo apt-get install wireguard openresolv
    - name: Create wireguard tunnel configuration
      shell: bash
      run: |
        touch tunnel.conf
        echo "[Interface]" >> tunnel.conf
        echo "PrivateKey = ${{ inputs.interface_private_key }}" >> tunnel.conf
        echo "Address = ${{ inputs.interface_address }}" >> tunnel.conf
        if [ -n "${{ inputs.interface_dns }}" ]; then
          echo "DNS = ${{ inputs.interface_dns }}" >> tunnel.conf
        fi
        
        echo -e "\n[Peer]" >> tunnel.conf
        echo "PublicKey = ${{ inputs.peer_public_key }}" >> tunnel.conf
        echo "AllowedIPs = ${{ inputs.peer_allowed_ips }}" >> tunnel.conf
        echo "Endpoint = ${{ inputs.peer_endpoint }}" >> tunnel.conf
        cat tunnel.conf
        sudo cp tunnel.conf /etc/wireguard/
        wg-quick up tunnel
